FROM public.ecr.aws/lambda/python:3.12
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY preprocess_power_level/ preprocess_power_level/
COPY libs/ libs/
COPY services/ services/
CMD ["preprocess_power_level.preprocess_power_level.lambda_handler"]
