FROM public.ecr.aws/lambda/python:3.12
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY api/ api/
COPY libs/ libs/
COPY services/ services/
CMD ["preproces_power_level.preprocess_power_level.lambda_handler"]
